Repository Team-SSOK/ssok-bank, pull requests merged in 2025-04, with the labels that each got.

#13 refactor: 계좌 조회 검증 필드 추가 및 공통 코드 정리 (#12, SCRUM-32)
  src/main/java/kr/ssok/bank/common/constant/BankCode.java
  src/main/java/kr/ssok/bank/common/constant/FailureStatusCode.java
  src/main/java/kr/ssok/bank/common/constant/SuccessStatusCode.java
  src/main/java/kr/ssok/bank/domain/account/controller/AccountController.java
  src/main/java/kr/ssok/bank/domain/account/service/AccountService.java
  src/main/java/kr/ssok/bank/domain/account/service/AccountServiceImpl.java
Labels: duplicate

#16 feat: 예금주명 조회 (#1, SCRUM-47)
  src/main/java/kr/ssok/bank/domain/account/controller/AccountController.java
  src/main/java/kr/ssok/bank/domain/account/dto/AccountOwnerCheckRequestDTO.java
  src/main/java/kr/ssok/bank/domain/account/dto/AccountOwnerCheckResponseDTO.java
  src/main/java/kr/ssok/bank/domain/account/repository/AccountRepository.java
  src/main/java/kr/ssok/bank/domain/account/service/AccountService.java
  src/main/java/kr/ssok/bank/domain/account/service/AccountServiceImpl.java
Labels: enhancement

#17 fix: 사용자 생성 관련 로직수정 (#2, SCRUM-78)
  src/main/java/kr/ssok/bank/domain/account/service/AccountService.java
  src/main/java/kr/ssok/bank/domain/user/controller/UserController.java
  src/main/java/kr/ssok/bank/domain/user/service/UserServiceImpl.java
Labels: enhancement

#20 fix: 휴면 계좌 조회 레포지토리 메서드 변경(#15, SCRUM-35)
  src/main/java/kr/ssok/bank/domain/account/service/AccountServiceImpl.java
Labels: bug

#21 feat: 계좌 유효성 검사 추가 (#19, SCRUM-34)
  src/main/java/kr/ssok/bank/common/constant/FailureStatusCode.java
  src/main/java/kr/ssok/bank/domain/account/controller/AccountController.java
  src/main/java/kr/ssok/bank/domain/account/dto/AccountBalanceRequestDTO.java
  src/main/java/kr/ssok/bank/domain/account/dto/AccountBalanceResponseDTO.java
  src/main/java/kr/ssok/bank/domain/account/dto/AccountTransferableCheckRequestDTO.java
  src/main/java/kr/ssok/bank/domain/account/dto/AccountTransferableCheckResponseDTO.java
  src/main/java/kr/ssok/bank/domain/account/dto/AccountValidRequestDTO.java
  src/main/java/kr/ssok/bank/domain/user/controller/UserController.java
Labels: enhancement

#23 feat: 계좌 잔액 및 송금 한도 검사
  src/main/java/kr/ssok/bank/domain/account/controller/AccountController.java
Labels: enhancement

#25 feat: 계좌 잔액 조회 요청
  src/main/java/kr/ssok/bank/domain/account/controller/AccountController.java
Labels: enhancement

#30 feat: 입/출금 로직 1차 구현 완료 (#26, #27, SCRUM-30, SCRUM-31)
  src/main/java/kr/ssok/bank/domain/account/entity/Account.java
  src/main/java/kr/ssok/bank/domain/account/repository/AccountRepository.java
  src/main/java/kr/ssok/bank/domain/transfer/controller/TransferController.java
  src/main/java/kr/ssok/bank/domain/transfer/dto/TransferDepositRequestDTO.java
  src/main/java/kr/ssok/bank/domain/transfer/dto/TransferRequestDTO.java
  src/main/java/kr/ssok/bank/domain/transfer/dto/TransferWithdrawRequestDTO.java
  src/main/java/kr/ssok/bank/domain/transfer/entity/TransferHistory.java
  src/main/java/kr/ssok/bank/domain/transfer/repository/TransferRepository.java
  src/main/java/kr/ssok/bank/domain/transfer/service/TransferService.java
  src/main/java/kr/ssok/bank/domain/transfer/service/TransferServiceImpl.java
Labels: enhancement

#31 docs: swagger 적용(#26, SCRUM-31)
  src/main/java/kr/ssok/bank/domain/transfer/controller/TransferController.java
Labels: documentation

#32 feat: 계좌 거래 내역 조회 요청
  build.gradle
  src/main/java/kr/ssok/bank/common/constant/CurrencyCode.java
  src/main/java/kr/ssok/bank/common/constant/TransferTypeCode.java
  src/main/java/kr/ssok/bank/domain/account/controller/AccountController.java
  src/main/java/kr/ssok/bank/domain/account/dto/AccountTransferHistoryRequestDTO.java
  src/main/java/kr/ssok/bank/domain/account/dto/AccountTransferHistoryResponseDTO.java
  src/main/java/kr/ssok/bank/domain/transfer/entity/TransferHistory.java
  src/main/java/kr/ssok/bank/domain/transfer/service/TransferServiceImpl.java
Labels: enhancement

#33 docs: Swagger 추가(#26, SCRUM-31)
  src/main/java/kr/ssok/bank/domain/account/controller/AccountController.java
Labels: documentation

#35 refactor: 계좌번호 채번 시 검증 번호 도입(#34, SCRUM-117)
  src/main/java/kr/ssok/bank/domain/account/controller/AccountController.java
  src/main/java/kr/ssok/bank/domain/account/service/AccountServiceImpl.java
Labels: duplicate

#37 test: service layer 테스트 코드 추가(#36, SCRUM-129)
  src/main/java/kr/ssok/bank/common/entity/TimeStamp.java
  src/main/java/kr/ssok/bank/domain/account/service/AccountServiceImpl.java
  src/test/java/kr/ssok/bank/SsokBankApplicationTests.java
  src/test/java/kr/ssok/bank/domain/account/service/AccountServiceImplTest.java
  src/test/java/kr/ssok/bank/domain/transfer/service/TransferServiceImplTest.java
  src/test/java/kr/ssok/bank/domain/user/service/UserServiceImplTest.java
Labels: enhancement

#40 refactor: REST API 메서드 일부 변경( #39, SCRUM-135)
  src/main/java/kr/ssok/bank/domain/account/controller/AccountController.java
  src/main/java/kr/ssok/bank/domain/account/dto/AccountRequestDTO.java
Labels: enhancement

#41 feat: 예금 상품 이자 계산 로직 추가(#38, SCRUM-118)
  .gitignore
  src/main/java/kr/ssok/bank/SsokBankApplication.java
  src/main/java/kr/ssok/bank/common/constant/FailureStatusCode.java
  src/main/java/kr/ssok/bank/common/constant/SuccessStatusCode.java
  src/main/java/kr/ssok/bank/common/constant/TransferTypeCode.java
  src/main/java/kr/ssok/bank/domain/account/controller/AccountController.java
  src/main/java/kr/ssok/bank/domain/account/entity/Account.java
  src/main/java/kr/ssok/bank/domain/account/repository/AccountRepository.java
  src/main/java/kr/ssok/bank/domain/good/controller/GoodController.java
  src/main/java/kr/ssok/bank/domain/good/dto/GoodResponseDTO.java
  src/main/java/kr/ssok/bank/domain/good/entity/Good.java
  src/main/java/kr/ssok/bank/domain/good/repository/GoodRepository.java
  src/main/java/kr/ssok/bank/domain/good/service/GoodService.java
  src/main/java/kr/ssok/bank/domain/good/service/GoodServiceImpl.java
  src/main/java/kr/ssok/bank/scheduler/InterestScheduler.java
  src/main/resources/application.yml
  src/main/resources/db/init.sql
Labels: enhancement

#42 fix: 사용하지 않는 의존성 제거(#38, SCRUM-118)
  src/main/java/kr/ssok/bank/domain/good/service/GoodService.java
Labels: bug, enhancement

#43 fix: mapping 오류 해결(#38, SCRUM-118)
  src/main/java/kr/ssok/bank/domain/good/entity/Good.java
Labels: bug

#45 fix: 계좌 개설 중 good 매칭 안되는 오류 해결 및 AESUtil 추가(#44, SCRUM-140)
  src/main/java/kr/ssok/bank/common/constant/FailureStatusCode.java
  src/main/java/kr/ssok/bank/common/util/AESUtil.java
  src/main/java/kr/ssok/bank/domain/account/controller/AccountController.java
  src/main/java/kr/ssok/bank/domain/account/service/AccountService.java
  src/main/java/kr/ssok/bank/domain/account/service/AccountServiceImpl.java
  src/main/java/kr/ssok/bank/domain/good/repository/GoodRepository.java
  src/main/resources/application.yml
Labels: bug, enhancement
