Repository Team-SSOK/ssok-bank, pull requests merged in 2025-05, with the labels that each got.

#49 feat: kafka 리스너 소스 분리, 로직 추가 (#46, SCRUM-137)
  src/main/java/kr/ssok/bank/domain/good/entity/Good.java
  src/main/java/kr/ssok/bank/domain/transfer/listener/TransferListener.java
  src/main/java/kr/ssok/bank/domain/transfer/service/TransferServiceImpl.java
Labels: enhancement

#50 fix: 계좌 유효성 검사 수정 (#46, SCRUM-137)
  src/main/java/kr/ssok/bank/domain/account/controller/AccountController.java
Labels: bug

#51 fix: 복호화 오류 확인 로그 추가 (#44, SCRUM-140)
  src/main/java/kr/ssok/bank/domain/transfer/service/TransferServiceImpl.java
  src/main/resources/db/init.sql
Labels: bug

#52 fix: 암복호화 오류 해결을 위한 로직 추가(#44, SCRUM-140)
  src/main/java/kr/ssok/bank/common/constant/FailureStatusCode.java
  src/main/java/kr/ssok/bank/domain/transfer/service/TransferServiceImpl.java
Labels: bug

#53 fix: 계좌번호 비교 시 암호화된 번호로 확인(#44, SCRUM-140)
  src/main/java/kr/ssok/bank/domain/transfer/service/TransferServiceImpl.java
Labels: bug

#59 feat: 카프카 수정 및 JsonUtil 추가 (#46, SCRUM-137)
  src/main/java/kr/ssok/bank/common/comm/JsonUtil.java
  src/main/java/kr/ssok/bank/common/config/KafkaConfig.java
  src/main/java/kr/ssok/bank/common/response/ApiResponse.java
  src/main/java/kr/ssok/bank/domain/transfer/listener/TransferListener.java
Labels: bug

#61 fix: kafka dto 경로 수정 (#56, SCRUM-150)
  src/main/java/kr/ssok/bank/domain/transfer/dto/CompensateRequestDTO.java
  src/main/java/kr/ssok/bank/domain/transfer/listener/TransferListener.java
  src/main/java/kr/ssok/bank/domain/transfer/service/TransferServiceImpl.java
  src/test/java/kr/ssok/bank/domain/transfer/service/TransferServiceImplTest.java
Labels: bug

#62 refactor: 출금 중 잔액 부족 시 데이터 확인을 위해 로그 추가(#56, SCRUM-150)
  src/main/java/kr/ssok/bank/domain/transfer/service/TransferServiceImpl.java
Labels: documentation

#64 feat: 카프카 메세지 타임아웃 방지 로직 추가(#63, SCRUM-165)
  src/main/java/kr/ssok/bank/common/constant/FailureStatusCode.java
  src/main/java/kr/ssok/bank/domain/transfer/dto/TransferDepositRequestDTO.java
  src/main/java/kr/ssok/bank/domain/transfer/dto/TransferWithdrawRequestDTO.java
  src/main/java/kr/ssok/bank/domain/transfer/listener/TransferListener.java
Labels: enhancement

#65 fix: 트랜잭션 관련 isExpired() 수정 (#63, SCRUM-165)
  src/main/java/kr/ssok/bank/domain/transfer/listener/TransferListener.java
Labels: enhancement

#67 feat: Enum valueof() 추가 (#63, SCRUM-165)
  src/main/java/kr/ssok/bank/common/constant/AccountTypeCode.java
  src/main/java/kr/ssok/bank/common/constant/BankCode.java
  src/main/java/kr/ssok/bank/common/constant/UserTypeCode.java
Labels: enhancement

#68 feat: 동일한 번호로 가입된 사용자가 있는데 이름이 다를 경우 예외 처리(#2, SCRUM-78)
  src/main/java/kr/ssok/bank/common/constant/FailureStatusCode.java
  src/main/java/kr/ssok/bank/domain/user/repository/UserRepository.java
  src/main/java/kr/ssok/bank/domain/user/service/UserServiceImpl.java
Labels: enhancement

#69 feat: withdraw/deposit/compensate에 유효하지 않은 금액 예외 처리 (#26, SCRUM-31)
  src/main/java/kr/ssok/bank/common/constant/FailureStatusCode.java
  src/main/java/kr/ssok/bank/domain/transfer/service/TransferServiceImpl.java
Labels: enhancement

#70 refactor: 테스트 용 초기 금액 셋팅(#1, SCRUM-47)
  src/main/java/kr/ssok/bank/domain/account/service/AccountServiceImpl.java
Labels: documentation

#71 fix: 충돌 해결 중 누락된 메서드 추가(#1, SCRUM-47)
  src/main/java/kr/ssok/bank/domain/account/service/AccountServiceImpl.java
Labels: bug

#72 feat: 테스트 목적 계좌 추가 개설 로직 수정(#1, SCRUM-47)
  src/main/java/kr/ssok/bank/domain/account/controller/AccountController.java
  src/main/java/kr/ssok/bank/domain/account/service/AccountService.java
  src/main/java/kr/ssok/bank/domain/account/service/AccountServiceImpl.java
Labels: enhancement

#73 feat: 은행 별 prefix 적용(#1, SCRUM-47)
  src/main/java/kr/ssok/bank/domain/account/service/AccountServiceImpl.java
  src/main/java/kr/ssok/bank/domain/user/entity/User.java
Labels: enhancement
